config/routes.rb
Rails.application.routes.draw do
  get 'squads/index'
  get 'persons/index'
  get 'comicbooks/index'
  get 'comicbooks/create'
  get 'comicbooks/new'
  get 'comicbooks/edit'
  get 'comicbooks/update'
  #devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'application#welcome'

 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
 # New naming conventions
 
resources :comicbooks, only: %i[index new create edit update destroy]
resources :persons do
  resources :comicbooks, only: [:index, :new]
end

resources :squads
 
 
#  # Old naming conventions
#     get 'heros/index'
#     get 'heros/show'
#     get 'heros/new'
#     get 'heros/create'
  
#     resources :heros
#     resources :comics

end

app/models/comicbook.rb
class Comicbook < ApplicationRecord
  belongs_to :person
  belongs_to :squad
  validates :title, presence: true, uniqueness: { scope: :person }


  # scope :search, => (search) do
  #   return if search.blank?
  #   where('name Like ?', "%#{:search}%")
  # end

  # searchable do
  #   text :name, :title
  # end

  # def self.search(search)
  #   if search
  #     comicbook_type = Comicbook.find_by(title: search)
  #     if comicbook_type
  #       self.where(comicbook_id: comicbook_type)
  #     else
  #       @comicbooks = Comicbook.all
  #     end
  #   else
  #     @comicbooks = Comicbook.all
  #   end
  # end


def self.filter_by_name(search)
  if search
    where('title Like ?', "%#{search}%")
  else
    all
  end
end

  def person_attributes=(args)
    self.person = Person.find_or_create_by(args)
  end

  def squad_attributes=(args)
    self.squad = Squad.find_or_create_by(args)
  end
end

app/controllers/comicbooks_controller.rb
class ComicbooksController < ApplicationController
  before_action :set_comicbook, only: [:show]
  has_scope :search

  def index
    
      if params[:person_id]
        # This is the nested route, /person/:author_id/comicbooks
        person = Person.find_by(id: params[:person_id])
        @comicbooks = person.comicbooks
      elsif params[:search].present?
        @comicbooks = Comicbook.filter_by_name(params[:search]) 
      else 
        @comicbooks = Comicbook.all
    end
  end 

 


  def create
    @comicbook = Comicbook.new(comicbook_params)
    
    if @comicbook.save
      redirect_to comicbooks_url
    else
      @errors = @comicbook.errors.full_messages
      render :new
    end
  end

  def show
    @comicbook = Comicbook.find(comicbook_params[:id])
  end

  def new
    @comicbook = Comicbook.new(person_id: params[:person_id])
    @comicbook.person = Person.new
    @comicbook.squad = Squad.new
  end

  def edit
    if params[:person_id]
      person = Person.find_by(id: params[:person_id])
      if person.nil?
        redirect_to persons_path, alert: "person not found."
      else
        @comicbook = person.comicbooks.find_by(id: params[:id])
        redirect_to person_comicbooks_path(person), alert: "comicbook not found." if @comicbook.nil?
      end
    else
      @comicbook = Comicbook.find(params[:id])
    end
  end

  # def edit
  #   unless @comicbook = Comicbook.find_by_id(params[:id])
  #     @error = ['Comicbook Not Found']
  #     redirect_to comicbooks_url
  #   end
  # end

  def update
    @comicbook = Comicbook.find(params[:id])
    @comicbook.update(comicbook_params)
    redirect_to comicbooks_path(@comicbook),
    alert: "Edited"
    
  end

  def destroy
    @comicbook = Comicbook.find(params[:id])
    @comicbook.destroy
    redirect_to comicbooks_url,
    alert: "Deleted"
  end

  private

  def set_comicbook
    unless @comicbook = Comicbook.find_by_id(params[:id])
      redirect_to comicbooks_path
    end
  end

  def comicbook_params
    params.require(:comicbook).permit(:person_id, :starts_with, :title, :search, :comicbook_id, :name, person_attributes: [:name], squad_attributes: [:name])
  end

 
  
  # def destroy
  #   @comicbook = Comicbook.find(params[:id])
  #   @comicbook.destroy
  #   redirect_to comicbooks_path
  # end
end

app/helpers/comicbooks_helper.rb
module ComicbooksHelper
end

app/views/comicbooks/_all_comicbooks.html.erb
<table>
    <tr>
        <th>Hero</th>
        <th>Squad</th>
        <th>Comicbook</th>
    </tr>
    <% comicbooks.each do |comicbook| %>
    <% render partial: 'comicbooks/comicbook', locals: {comicbook: comicbook }%>
    <% end %>
    
</table>

app/views/comicbooks/_comicbook.html.erb
<tr>
    <td><%= comicbook.person.name %></td>
    <td><%= comicbook.squad.name %></td>
    <!-- <td><%= comicbook.title %></td> -->
    <td><li><%= link_to comicbook.title, person_comicbooks_url(comicbook) %></li><td></td>

    <td><%= link_to "Edit", edit_comicbook_path(comicbook)%></td>
    <td><%= link_to "Delete", comicbook, :confirm => "Really?", :method => :delete %></td>
    
</tr>

app/views/comicbooks/_form.html.erb
<%= form_for comicbook do |f| %>
    <%= f.hidden_field :person_id %>
    <p>
        <%= f.fields_for :person do |person|  %>
            <%= person.label :person %>
            <%= person.text_field :name %>
        <% end %>
    </p>
    <p>
    <%= f.fields_for :squad do |squad|  %>
        <%= squad.label :team %>
        <%= squad.text_field :name %>
    <% end %>
    </p>

    <p>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </p>
   

    <%= f.submit %>
<% end %>

app/views/comicbooks/create.html.erb
<h1>Comicbooks#create</h1>
<p>Find me in app/views/comicbooks/create.html.erb</p>

app/views/comicbooks/edit.html.erb
<h1>Comicbooks</h1>
<%= render partial: 'form', locals: { comicbook: @comicbook } %>
<p><%= link_to "Back to Comicbooks", comicbooks_path(@event)  %></p>

app/views/comicbooks/index.html.erb
<h1>Your List</h1>

<!-- <h4>Search By Team</h4> -->
    <%= form_tag comicbooks_path, :method => :get do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search" , :name => nil %>
    <% end %>

    <table >
        <tr >
            <th class="tableheader">Hero</th>
            <th class="tableheader">Team</th>
            <th class="tableheader">Comicbooks</th>
        </tr>
            <% @comicbooks.each do |comicbook| %>
            <!-- <%= render partial: 'comicbooks/all_comicbooks', locals: {comicbooks: @comicbooks} %> -->
            <%= render partial: 'comicbook', locals: {comicbook: comicbook }%>
            <% end %>
    </table>
    <div class="vertical_spacer"><br></div>
    <%= link_to :'New Book', new_comicbook_path %>

app/views/comicbooks/new.html.erb
<h1>Create New Entry</h1>

<%= render partial: 'form', locals: { comicbook: @comicbook } %>

app/views/comicbooks/search.html.erb
<h1>Search Results</h1>
<%= render @comicbooks%>

app/views/comicbooks/show.html.erb
<h1><%= @comicbook.title %></h1>
<p>With <%= @comicbook.person.name %></p>

app/views/comicbooks/update.html.erb
<h1>Comicbooks#update</h1>


<p>Find me in app/views/comicbooks/update.html.erb</p>