config/routes.rb
Rails.application.routes.draw do
  get 'squads/index'
  get 'persons/index'
  get 'comicbooks/index'
  get 'comicbooks/create'
  get 'comicbooks/new'
  get 'comicbooks/edit'
  get 'comicbooks/update'
  #devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'application#welcome'

 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
 # New naming conventions
 
resources :comicbooks, only: %i[index new create edit update destroy]
resources :persons do
  resources :comicbooks, only: [:index, :new]
end

resources :squads
 
 
#  # Old naming conventions
#     get 'heros/index'
#     get 'heros/show'
#     get 'heros/new'
#     get 'heros/create'
  
#     resources :heros
#     resources :comics

end

app/models/person.rb
class Person < ApplicationRecord
    has_many :comicbooks
    has_many :squads, through: :comicbooks

    validates :name, presence: true, uniqueness: true
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  # byebug
  def index
    @persons = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/persons/index.html.erb
<h1>Your Heroes</h1>

<ul>
    <% @persons.each do |person| %>
        <li><%= link_to person.name, person_comicbooks_path(person) %></li>
        <% end %>
</ul>

app/views/persons/show.html.erb
<h1><%= @person.name %></h1>

<%= link_to "New Post", new_person_com_path(@person) %>
 
<p>Comicbooks:</p>
<% @person.comicbooks.each do |comicbook| %>
  <div><%= comicbook.title %></div>
<% end %>

<!-- <ul>
    <% @comicbooks.each do |comicbook| %>
        <li><%= link_to comicbook.title, person_comicbook_path(comicbook.person,comicbook) %></li>
    <% end %>
</ul> -->

<%= link_to 'Add New', new_person_comicbook_path(@person) %>