config/routes.rb
Rails.application.routes.draw do
  get 'squads/index'
  get 'persons/index'
  get 'comicbooks/index'
  get 'comicbooks/create'
  get 'comicbooks/new'
  get 'comicbooks/edit'
  get 'comicbooks/update'
  #devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'application#welcome'

 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
 # New naming conventions
 
resources :comicbooks, only: %i[index new create edit update destroy]
resources :persons do
  resources :comicbooks, only: [:index, :new]
end

resources :squads
 
 
#  # Old naming conventions
#     get 'heros/index'
#     get 'heros/show'
#     get 'heros/new'
#     get 'heros/create'
  
#     resources :heros
#     resources :comics

end

app/models/squad.rb
class Squad < ApplicationRecord
    has_many :comicbooks
    has_many :people, through: :comicbooks

    validates :name, presence: true, uniqueness: true
end

app/controllers/squads_controller.rb
class SquadsController < ApplicationController
  def index
    @squads = Squad.all
  end

  def show
    @squad = Squad.find(params[:id])
    # binding.pry
  end


end

app/helpers/squads_helper.rb
module SquadsHelper
end

app/views/squads/index.html.erb
<h1>Squads</h1>
<% @squads.each do |squad| %>
    <h2><% squad.name %></h2>
    <% render partial: 'comicbooks/all_comicbooks', locals: {comicbooks: squad.comicbooks }%>
<% end %>

app/views/squads/show.html.erb
<h1><%= @squad.name %></h1>

 
<p>Squad:</p>
<% @squad.people.each do |person| %>
  <div><%= link_to person.name, person_path(person) %></div>
<% end %>